---
author: "Nicholas Spyrison"
date: 2019-01-24
linktitle: PDF Sense Manual tours
title: PDF Sense Manual tours
# categories: [ "Development", "hugo" ]
# tags: ["hugo", "theme", "html", "css"]
weight: 10
---
```{r, include=F}
library(spinifex)
# fig 7
load("../../data/jetsProj_sub.rda")
load("../../data/PDFSense_fig7_basis.rda")
# fig 8
load("../../data/grDIScenter.rda")
load("../../data/PDFSense_fig8l_basis.rda")
```

[PDSSense paper - google scholar link](https://scholar.google.com/scholar?cluster=9110690189452049647&hl=en&as_sdt=0,5)



### Manual Tours from figure 7
```{r, warning=F}
# Fig 7, subset to ATLAS7old and ATLAS7new
view_basis(fig7_basis)
play_manual_tour(data = jetsProj_sub[, 1:4], basis = fig7_basis, manip_var = 3,
                 cat_var = jetsProj_sub$exp, render_type = render_gganimate)
play_manual_tour(data = jetsProj_sub[, 1:4], basis = fig7_basis, manip_var = 3,
                 cat_var = jetsProj_sub$exp)
# play_manual_tour(data = jetsProj_sub[, 1:4], basis = fig7_basis, manip_var = 4,
#                  cat_var = jetsProj_sub$exp)
```

### Manual Tours from figure 8
```{r, warning=F}
# Fig 8,
view_basis(fig8l_basis)
# play_manual_tour(data = grDIScenter[, 1:6], basis = fig8l_basis, manip_var = 6,
#                  cat_var = grDIScenter$disID)
# play_manual_tour(data = grDIScenter[, 1:6], basis = fig8l_basis, manip_var = 5,
#                  cat_var = grDIScenter$disID)
```
