---
author: "Nicholas Spyrison"
date: 2019-01-26
linktitle: PDF Sense Manual tour - Figure 7
title: PDF Sense Manual tour - 
# categories: [ "Development", "hugo" ]
# tags: ["hugo", "theme", "html", "css"]
# weight: 10
---

```{r, include=F}
library(spinifex)
# fig 7
load("../../data/jetsProj_sub.rda")
load("../../data/fig7_basis_1off.rda")
```


### Manual Tours from figure 7
```{r, warning=F}
# Fig 7, subset to ATLAS7old and ATLAS7new
view_basis(fig7_basis, labels = colnames(jetsProj_sub[, 1:4]))
play_manual_tour(data = jetsProj_sub[, 1:4], basis = fig7_basis, manip_var = 3,
                 cat_var = jetsProj_sub$exp)
```

Manipulating PC3 rotates variation of ATLAS7new out of the projection.

```{r}
play_manual_tour(data = jetsProj_sub[, 1:4], basis = fig7_basis, manip_var = 4,
                 cat_var = jetsProj_sub$exp)
```

Manipulating PC4 rotates some variation of ATLAS7nold out of the projection.

[PDS Sense paper - google scholar link](https://scholar.google.com/scholar?cluster=9110690189452049647&hl=en&as_sdt=0,5)
